<?php
namespace AsseticBundleTest;

use AsseticBundle;
use Zend\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-17 at 11:53:23.
 */
class FilterManager extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AsseticBundle\FilterManager
     */
    protected $object;

    /**
     * @var ServiceManager\ServiceManager
     */
    protected $service;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->service = new ServiceManager\ServiceManager();
        $this->object = new AsseticBundle\FilterManager();
        $this->object->setServiceLocator($this->service);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    public function testGetServiceLocator() {
        $this->assertSame($this->service, $this->object->getServiceLocator());
    }

    /**
     * @dataProvider getAliasProvider
     */
    public function testHasFalse($alias) {
        $this->assertFalse($this->object->has($alias));
    }

    public function getAliasProvider() {
        return array(
            'simple' => array(
                '$alias' => 'simpleName',
            ),
            'invalid name' => array(
                '$alias' => '@_simpleName',
            ),
        );
    }
}
